FROM registry.access.redhat.com/ubi8/ubi:8.5 AS builder
RUN dnf install -y golang && dnf clean all
WORKDIR /go/src/github.com/vrutkovs/cluster-ninja
COPY backend/ .
RUN go mod vendor && go build ./cmd/cluster-ninja/


FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5
COPY --from=builder /go/src/github.com/vrutkovs/cluster-ninja/cluster-ninja /bin/cluster-ninja
WORKDIR /srv
ENTRYPOINT ["/bin/cluster-ninja"]
