apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: cluster-ninja
  labels:
    app: cluster-ninja
spec:
  lookupPolicy:
    local: false
  tags:
  - importPolicy: {}
    name: backend
    referencePolicy:
      type: Source
  - importPolicy: {}
    name: frontend
    referencePolicy:
      type: Source
