apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-ninja
  annotations:
    route.openshift.io/termination: edge
spec:
  rules:
  - hosts: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 8080
        path: /
        pathType: Prefix
      - backend:
          serviceName: backend
          servicePort: 8080
        path: /api
        pathType: Prefix
  tls:
  - hosts:
    - foo.bar.com
