kind: Job
apiVersion: batch/v1
metadata:
  name: run-pipeline-post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: build-pipeline
          image: gcr.io/tekton-releases/dogfooding/tkn:latest
          command:
          - tkn
          - pipeline
          - start
          - build-pipeline
      serviceAccountName: pipeline
      restartPolicy: OnFailure
