kind: Job
apiVersion: batch/v1
metadata:
  name: run-pipeline-post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: build-pipeline
          image: gcr.io/tekton-releases/dogfooding/tkn:latest
          command:
          - tkn
          - pipeline
          - start
          - build-pipeline
          - --workspace
          - name=source,claimName=builds
          - --param
          - namespace=cluster-ninja
          - --param
          - gitUrl=https://github.com/vrutkovs/cluster-ninja.git
          - --param
          - gitRevision=main
      serviceAccountName: pipeline
      restartPolicy: OnFailure
