apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-ninja
  namespace: openshift-gitops
spec:
  destination:
    namespace: cluster-ninja
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: manifests
    repoURL: 'https://github.com/vrutkovs/cluster-ninja'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
      - /spec/template/spec/containers/0/image
