apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: build-pipeline
  namespace: openshift-gitops
spec:
  destination:
    namespace: build-pipeline
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: manifests/pipeline
    repoURL: 'https://github.com/vrutkovs/cluster-ninja'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
