kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: allow-pushes-from-build-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: build-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: promotion-role
