
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: promotion-role
rules:
- apiGroups: ["image.openshift.io"]
  resources: ["imagestreams", "images"]
  verbs: ["get", "create", "update", "patch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
